language: node_js
node_js:
  - "8"
before_install:
  - npm cache clean --force
  - npm cache verify
  - npm install npm@5.2.0 --global --loglevel=error --depth=0
install:
  - npm install --loglevel=error --depth=0
env:
  - CXX=g++-4.9
addons:
  mariadb: '10.3'
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
branches:
  only:
    - main
